# Then deploy to prod with
# api/aws-ecs-restart-gluroo-prod-backend
name: Check types and lint
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install lib dependencies
        run: node index.js